server:
  port: 8089
spring:
  profiles:
    active: ${PROFILE:test}
  datasource:
    password: ${DB_PASSWORD:mysecretpassword}
    url: jdbc:postgresql://${DB_HOSTNAME:localhost}:${DB_PORT:5889}/${DB_SCHEMA:postgres}
    username: ${DB_USERNAME:postgres}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true